/******************************************************************************
 * @file    PrintPL.h
 * @brief   Obsługa polskich znaków dla klasy Print.            // Polish character support for the Print class.
 *
 * Moduł umożliwia wyświetlanie tekstów UTF-8 z polskimi znakami // The module enables displaying UTF-8 text with Polish
 * na wyświetlaczach wykorzystujących zmodyfikowane fonty       // characters on displays using modified Adafruit GFX
 * Adafruit GFX.                                                // fonts.
 *
 * Autor: Waldemar Brzeziński                                  // Author: Waldemar Brzeziński
 ******************************************************************************/

#ifndef PRINTPL_H
#define PRINTPL_H

#include <Print.h>

/**
 * @brief Wyświetla tekst UTF-8 z obsługą polskich znaków.      // Displays UTF-8 text with Polish character support.
 *
 * Funkcja analizuje tekst zapisany w UTF-8 i zamienia polskie // The function analyzes UTF-8 encoded text and converts
 * litery na wewnętrzne kody znaków (0x80...0x91), zgodne ze   // Polish letters to internal character codes (0x80...0x91)
 * zmodyfikowanym fontem wygenerowanym przez fontconvert.      // compatible with the modified font generated by fontconvert.
 *
 * @param out  Obiekt klasy Print (np. wyświetlacz, Serial).   // @param out  Print class object (e.g. display, Serial).
 * @param text Tekst zakończony znakiem '\0'.                  // @param text Null-terminated text.
 */
void printPL(Print &out, const char *text);

#endif